import Foundation
import GitEngine

/// Resolves a `WorkspaceContext` for a directory: git state, project/package
/// detection, nested/multiple-repo detection, and generated/build/dependency
/// folder detection. Pure file + git inspection — no mutation.
public struct WorkspaceResolver {
    private static let skipDirs: Set<String> = [".git", ".build", ".swiftpm", "DerivedData", "Pods", "node_modules", "Carthage"]

    public init() {}

    public func resolve(_ url: URL, at date: Date = Date()) -> WorkspaceContext {
        let fm = FileManager.default
        var warnings: [WorkspaceWarning] = []

        // --- Git state (via GitEngine) ---
        let repo = GitRepository(repositoryURL: url)
        let isGit = repo.isGitRepository()
        var repoRoot: URL?
        var branch: String?
        var commit: String?
        var dirty = false
        var detached = false
        if isGit {
            repoRoot = (try? repo.runner.runChecked(["rev-parse", "--show-toplevel"]))?
                .trimmingCharacters(in: .whitespacesAndNewlines)
                .nonEmpty.map { URL(fileURLWithPath: $0) }
            let b = (try? repo.currentBranch()) ?? ""
            branch = b
            detached = (b == "HEAD")
            commit = (try? repo.runner.runChecked(["rev-parse", "--short", "HEAD"]))?
                .trimmingCharacters(in: .whitespacesAndNewlines)
            dirty = !((try? repo.status())?.isEmpty ?? true)
        } else {
            warnings.append(.init(severity: .info, code: .notAGitRepo,
                                  message: "This folder is not a Git repository — version control safety is unavailable."))
        }

        // --- Git operation / lock state (filesystem inspection of .git) ---
        let gitDir = (repoRoot ?? url).appendingPathComponent(".git")
        var operation: String?
        if fm.fileExists(atPath: gitDir.appendingPathComponent("MERGE_HEAD").path) { operation = "merge" }
        if fm.fileExists(atPath: gitDir.appendingPathComponent("rebase-merge").path)
            || fm.fileExists(atPath: gitDir.appendingPathComponent("rebase-apply").path) { operation = "rebase" }
        let hasLock = fm.fileExists(atPath: gitDir.appendingPathComponent("index.lock").path)

        // --- File scan (bounded depth, skipping noise dirs) ---
        var packages: [URL] = []
        var xcodeProjects: [URL] = []
        var workspaces: [URL] = []
        var nestedRepos: [URL] = []
        var swiftCount = 0
        var uiCount = 0
        if let en = fm.enumerator(at: url, includingPropertiesForKeys: [.isDirectoryKey], options: [.skipsHiddenFiles]) {
            for case let item as URL in en {
                let name = item.lastPathComponent
                let isDir = (try? item.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) ?? false
                if isDir {
                    if Self.skipDirs.contains(name) { en.skipDescendants(); continue }
                    if name.hasSuffix(".xcodeproj") { xcodeProjects.append(item); en.skipDescendants() }
                    else if name.hasSuffix(".xcworkspace") { workspaces.append(item); en.skipDescendants() }
                    else if item.standardizedFileURL != url.standardizedFileURL,
                            fm.fileExists(atPath: item.appendingPathComponent(".git").path) {
                        nestedRepos.append(item)
                    }
                    continue
                }
                if name == "Package.swift" { packages.append(item) }
                if item.pathExtension == "swift" {
                    swiftCount += 1
                    if let text = try? String(contentsOf: item, encoding: .utf8), text.contains(": View") {
                        uiCount += 1
                    }
                }
            }
        }

        // --- Generated-export / build / dependency heuristics ---
        let hasExportReport = fm.fileExists(atPath: url.appendingPathComponent("EXPORT_REPORT.md").path)
        let generatedPackage: Bool = {
            guard let pkg = packages.first, pkg.deletingLastPathComponent().standardizedFileURL == url.standardizedFileURL,
                  let text = try? String(contentsOf: pkg, encoding: .utf8) else { return false }
            return text.contains("Generated by Visual UI Architect")
        }()
        let looksGenerated = hasExportReport || generatedPackage
        let path = url.standardizedFileURL.path
        let looksBuild = url.lastPathComponent == ".build" || path.contains("/.build/")
        let looksDependency = path.contains("/checkouts/") || path.contains("/SourcePackages/")

        // --- Warnings ---
        if looksGenerated { warnings.append(.init(severity: .error, code: .generatedExportFolder,
            message: "This looks like a generated export package, not the source application repository.")) }
        if looksBuild { warnings.append(.init(severity: .error, code: .buildFolderSelected,
            message: "This is a build output directory (.build) — not a source repository.")) }
        if looksDependency { warnings.append(.init(severity: .error, code: .dependencyFolderSelected,
            message: "This is a checked-out dependency, not your source repository.")) }
        if !nestedRepos.isEmpty { warnings.append(.init(severity: .warning, code: .nestedRepos,
            message: "\(nestedRepos.count) nested Git repository(ies) found — confirm the intended repo.")) }
        if packages.count > 1 { warnings.append(.init(severity: .warning, code: .multiplePackages,
            message: "\(packages.count) Package.swift files found — confirm the target package.")) }
        if xcodeProjects.count > 1 { warnings.append(.init(severity: .warning, code: .multipleXcodeProjects,
            message: "\(xcodeProjects.count) .xcodeproj files found.")) }
        if workspaces.count > 1 { warnings.append(.init(severity: .warning, code: .multipleWorkspaces,
            message: "\(workspaces.count) .xcworkspace files found.")) }
        if detached { warnings.append(.init(severity: .warning, code: .detachedHEAD,
            message: "Repository is in detached-HEAD state — commits may be lost on checkout.")) }
        if let operation { warnings.append(.init(severity: .error, code: .operationInProgress,
            message: "A \(operation) is in progress — finish it before writing.")) }
        if hasLock { warnings.append(.init(severity: .warning, code: .indexLock,
            message: "A Git index.lock is present — another Git process may be running.")) }
        if dirty { warnings.append(.init(severity: .info, code: .dirtyTree,
            message: "The working tree has uncommitted changes.")) }
        if uiCount == 0 && !looksGenerated && !looksBuild { warnings.append(.init(severity: .info, code: .noUISources,
            message: "No SwiftUI View sources detected in this folder.")) }

        return WorkspaceContext(
            rootURL: url, isGitRepo: isGit, repoRoot: repoRoot, branch: branch,
            latestCommit: commit, isDirty: dirty, detachedHEAD: detached,
            operationInProgress: operation, hasIndexLock: hasLock,
            packageManifests: packages, xcodeProjects: xcodeProjects, xcodeWorkspaces: workspaces,
            nestedGitRepos: nestedRepos, looksLikeGeneratedExport: looksGenerated,
            looksLikeBuildFolder: looksBuild, looksLikeDependencyFolder: looksDependency,
            swiftFileCount: swiftCount, uiSourceCount: uiCount, lastScan: date,
            warnings: warnings.sorted { $0.severity > $1.severity })
    }
}

private extension String {
    var nonEmpty: String? { isEmpty ? nil : self }
}
