import Foundation
import VUACore
import ControlBehaviourEngine

/// Generates production-quality SwiftUI from the layer tree.
///
/// Layout strategy: absolute placement inside a top-leading `ZStack`, using
/// `.frame` for size and `.position` for location, faithfully reproducing the
/// canvas. Each layer carries an `.accessibilityIdentifier` derived from its
/// code-binding anchor so visual edits can round-trip back to source.
public struct SwiftUIGenerator: CodeGenerator {
    public let target: CodeGenTarget = .swiftUI
    public var viewName: String
    /// Emit the `#Preview { ... }` macro block. Disable for exports targeting
    /// machines without Xcode (the macro plugin ships only with Xcode).
    public var includePreview: Bool

    public init(viewName: String = "GeneratedView", includePreview: Bool = true) {
        self.viewName = viewName
        self.includePreview = includePreview
    }

    public func generate(document: Document) throws -> GeneratedSource {
        var b = SourceBuilder()
        b.line("// swiftlint:disable all")
        b.line("//")
        b.line("//  \(viewName).swift")
        b.line("//  Generated by Visual UI Architect — do not hand-edit anchored regions.")
        b.line("//")
        b.line()
        b.line("import SwiftUI")
        if usesControlLibrary(document) {
            b.line("import VUAControls")
        }
        b.line()
        if !document.designTokens.isEmpty {
            emitDesignTokens(document.designTokens, into: &b)
            b.line()
        }
        b.block("struct \(viewName): View {") { b in
            b.block("var body: some View {") { b in
                b.block("ZStack(alignment: .topLeading) {") { b in
                    for layer in document.roots where layer.isVisible {
                        emit(layer, into: &b, document: document)
                    }
                }
                let size = document.canvasSize
                b.line("}")
                b.indented { b in
                    b.line(".frame(width: \(fmt(size.width)), height: \(fmt(size.height)), alignment: .topLeading)")
                }
            }
            b.line("}")   // close body
        }
        b.line("}")       // close struct

        // Emit one reusable struct per component master (Phase 15).
        for component in document.components {
            b.line()
            emitComponentStruct(component, into: &b, document: document)
        }

        if includePreview {
            b.line()
            b.line("#Preview {")
            b.indented { $0.line("\(viewName)()") }
            b.line("}")
        }
        b.line("// swiftlint:enable all")
        return GeneratedSource(fileName: "\(viewName).swift", contents: b.text)
    }

    // MARK: - Layer emission

    private func emitDesignTokens(_ tokens: [DesignToken], into b: inout SourceBuilder) {
        b.block("enum DesignTokens {") { b in
            for token in tokens {
                switch token.value {
                case .color(let color):
                    b.line("static let \(token.swiftName) = \(colorExpr(color))")
                case .typography(let size, let weight):
                    b.line("static let \(token.swiftName) = Font.system(size: \(fmt(size))\(weight.map { ", weight: .\($0.rawValue)" } ?? ""))")
                case .spacing(let value), .cornerRadius(let value):
                    b.line("static let \(token.swiftName): CGFloat = \(fmt(value))")
                case .shadow(let shadow):
                    b.line("static let \(token.swiftName) = (color: \(colorExpr(shadow.color)), radius: \(fmt(shadow.radius)), x: \(fmt(shadow.x)), y: \(fmt(shadow.y)))")
                case .gradient(let gradient):
                    b.line("static let \(token.swiftName) = \(gradientExpr(gradient))")
                case .material(let material):
                    b.line("static let \(token.swiftName): Material = .\(material)")
                }
            }
        }
    }

    private func emit(_ layer: Layer, into b: inout SourceBuilder, document: Document) {
        b.line("// MARK: \(layer.name) [\(layer.kind.displayName)]")
        if let c = layer.control {
            let unit = c.unit.symbol.isEmpty ? "" : " \(c.unit.symbol)"
            b.line("// AU param: \(c.parameterID) — \(fmt(c.minValue))…\(fmt(c.maxValue))\(unit), default \(fmt(c.defaultValue))\(unit)\(c.isContinuous ? "" : ", \(c.stepCount ?? 2) steps")")
            if let behaviour = ControlBehaviourResolver.profile(for: layer) {
                b.line("// Behaviour: \(behaviour.type.displayName), \(behaviour.interactionMode.rawValue), \(behaviour.responseCurve.rawValue), \(behaviour.isContinuous ? "continuous" : "\(behaviour.stepCount ?? 2)-step")")
                if let binding = behaviour.bindingName, !binding.isEmpty {
                    b.line("// Binding target: \(binding)")
                } else {
                    b.line("// Binding target: TODO connect \(behaviour.parameterID) to app/AU state")
                }
                if let midi = behaviour.midiCC {
                    b.line("// MIDI CC: \(midi)")
                }
                if behaviour.automationEnabled {
                    b.line("// Automation: enabled")
                }
            }
        }
        if let paint = layer.rasterPaint {
            b.line("// Raster paint: \(paint.strokes.count) stroke(s), tool \(paint.activeBrush.tool.rawValue), original asset preserved")
            if let name = paint.exportedAssetName {
                b.line("// Painted PNG asset: \(name)")
            }
        }
        b.block("Group {") { b in
            emitContent(layer, into: &b, document: document)
        }
        b.line("}")
        b.indented { b in
            emitModifiers(layer, into: &b, document: document)
        }
    }

    private func emitContent(_ layer: Layer, into b: inout SourceBuilder, document: Document) {
        // Component instance: collapse to a single component-view call (the
        // child clones exist for the editor; in code we reuse the master).
        if let cid = layer.componentID, let component = document.component(id: cid) {
            if let variant = component.variant(id: layer.componentVariantID) {
                b.line("\(component.generatedTypeName)(variant: \(quoted(variant.name)))")
            } else {
                b.line("\(component.generatedTypeName)()")
            }
            if !layer.componentOverrides.isEmpty {
                b.indented { b in
                    b.line("// VUA overrides: \(layer.componentOverrides.map { "\($0.property)=\($0.valueDescription)" }.joined(separator: ", "))")
                }
            }
            return
        }
        switch layer.kind {
        case .container, .panel, .background, .group:
            // Asset-backed panels/backgrounds emit a real Image so the export
            // pipeline can copy the file and the target project renders it
            // — matches the in-app canvas renderer.
            if let assetID = layer.assetID, let asset = document.asset(id: assetID) {
                b.line("Image(\(quoted(asset.name)))")
                b.indented { $0.line(".resizable()") }
            } else if layer.children.isEmpty {
                b.line(layer.style.backgroundColor != nil || layer.style.gradient != nil ? "Rectangle()" : "Color.clear")
            } else {
                b.block("ZStack(alignment: .topLeading) {") { b in
                    for child in layer.children where child.isVisible {
                        emit(child, into: &b, document: document)
                    }
                }
                b.line("}")
            }
        case .shape(let kind):
            emitShape(kind, layer, into: &b)
        case .line:
            emitLine(layer, into: &b)
        case .vectorPath:
            emitVectorPath(layer, into: &b)
        case .polygon:
            emitPolygon(layer, into: &b)
        case .gradient:
            b.line("Rectangle()")
            b.indented { $0.line(".fill(\(fillExpr(layer)))") }
        case .mask:
            // A mask layer's own rendering is its shape; the clipping is applied
            // to the group via the `.mask`/`.clipShape` modifier.
            b.line("\(shapeExpr(layer.mask?.shape ?? .rectangle, layer))")
            b.indented { $0.line(".fill(\(fillExpr(layer)))") }
        case .button:
            b.block("Button(action: {}) {") { b in
                b.line("Text(\(quoted(layer.text ?? layer.name)))")
            }
            b.line("}")
        case .label, .text:
            b.line("Text(\(quoted(layer.text ?? layer.name)))")
        case .image:
            if let assetID = layer.assetID, let asset = document.asset(id: assetID) {
                b.line("Image(\(quoted(asset.name)))")
                b.indented { $0.line(".resizable()") }
            } else {
                b.line("Image(systemName: \"photo\")")
                b.indented { $0.line(".resizable()") }
            }
        case .slider:
            let value = layer.control.map { fmt($0.normalizedDefault) } ?? "0.5"
            b.line("Slider(value: .constant(\(value)))")
        case .toggle:
            let on = (layer.control?.defaultValue ?? 1) >= 0.5 ? "true" : "false"
            b.line("Toggle(\(quoted(layer.text ?? layer.name)), isOn: .constant(\(on)))")
        case .knob, .fader, .meter, .control:
            // Plugin controls come from the VUAControls library, parameterised
            // by the layer's AU metadata (range, default, label).
            b.line(controlConstructor(for: layer))
        case .custom(let typeName):
            b.line("\(sanitizeType(typeName))()")
        }
    }

    /// View type a plugin control maps to. Uses a conventional name derived
    /// from the kind (e.g. `KnobView`) so generated code references a real,
    /// developer-provided control rather than a placeholder shape.
    private func controlViewName(for layer: Layer) -> String {
        switch layer.kind {
        case .knob: return "KnobView"
        case .fader: return "FaderView"
        case .meter: return "MeterView"
        default: return "ControlView"
        }
    }

    /// Emits a fully-parameterised VUAControls constructor for a plugin control.
    private func controlConstructor(for layer: Layer) -> String {
        let view = controlViewName(for: layer)
        let c = layer.control
        let defaultValue = c?.defaultValue ?? 0.5
        var args = ["value: .constant(\(fmt(defaultValue)))"]
        if let c {
            args.append("in: \(fmt(c.minValue))...\(fmt(c.maxValue))")
            // Only knob/fader expose a label argument in VUAControls.
            if layer.kind == .knob || layer.kind == .fader {
                args.append("label: \(quoted(c.displayName))")
            }
        }
        return "\(view)(\(args.joined(separator: ", ")))"
    }

    /// True when the document contains controls backed by the VUAControls library.
    private func usesControlLibrary(_ document: Document) -> Bool {
        if document.allLayers.contains(where: { isControl($0.kind) }) { return true }
        // Component masters can also drag in the controls library.
        return document.components.contains { component in
            component.master.flattened().contains { isControl($0.kind) }
                || component.variants.contains { $0.master.flattened().contains { isControl($0.kind) } }
        }
    }

    private func isControl(_ kind: LayerKind) -> Bool {
        switch kind { case .knob, .fader, .meter, .control: return true; default: return false }
    }

    /// Emits `struct <Name>ComponentView: View { var body: some View { … } }`
    /// for one component master. The master is rendered as a top-leading ZStack
    /// so embedded instance positions keep the same geometry as the canvas.
    private func emitComponentStruct(_ component: Component, into b: inout SourceBuilder, document: Document) {
        b.line("// MARK: Component — \(component.name)")
        b.block("struct \(component.generatedTypeName): View {") { b in
            b.line("var variant: String = \"Base\"")
            b.block("var body: some View {") { b in
                if component.variants.isEmpty {
                    emitComponentMaster(component.master, into: &b, document: document)
                } else {
                    b.block("Group {") { b in
                        b.block("switch variant {") { b in
                            for variant in component.variants {
                                b.line("case \(quoted(variant.name)):")
                                b.indented { inner in emitComponentMaster(variant.master, into: &inner, document: document) }
                            }
                            b.line("default:")
                            b.indented { inner in emitComponentMaster(component.master, into: &inner, document: document) }
                        }
                    }
                }
            }
            b.line("}")
        }
        b.line("}")
    }

    private func emitComponentMaster(_ master: Layer, into b: inout SourceBuilder, document: Document) {
        b.block("ZStack(alignment: .topLeading) {") { b in
            for child in master.children where child.isVisible {
                emit(child, into: &b, document: document)
            }
        }
        b.line("}")
        b.indented { b in
            b.line(".frame(width: \(fmt(master.frame.width)), height: \(fmt(master.frame.height)), alignment: .topLeading)")
        }
    }

    private func emitModifiers(_ layer: Layer, into b: inout SourceBuilder, document: Document) {
        let s = layer.style
        // Shapes/lines/polygons handle their own fill+stroke in content.
        let selfPaints = isVectorKind(layer.kind)

        if let fg = s.foregroundColor, !selfPaints {
            b.line(".foregroundStyle(\(tokenExpr(s.tokens.foregroundColor, document: document) ?? colorExpr(fg)))")
        }
        if let fontSize = s.fontSize {
            if let token = tokenExpr(s.tokens.typography, document: document) {
                b.line(".font(\(token))")
            } else {
                let weight = s.fontWeight.map { ".weight(.\($0.rawValue))" } ?? ""
                b.line(".font(.system(size: \(fmt(fontSize)))\(weight))")
            }
        }
        // Size first, then background/clip, then transform, then position.
        b.line(".frame(width: \(fmt(layer.frame.width)), height: \(fmt(layer.frame.height)))")
        if !selfPaints {
            if let gradient = s.gradient {
                b.line(".background(\(tokenExpr(s.tokens.gradient, document: document) ?? gradientExpr(gradient)))")
            } else if let bg = s.backgroundColor {
                b.line(".background(\(tokenExpr(s.tokens.backgroundColor, document: document) ?? colorExpr(bg)))")
            } else if let material = s.tokens.material, let name = tokenName(material, document: document) {
                b.line(".background(DesignTokens.\(name))")
            }
        }
        // Explicit clip shape (mask) takes priority over corner-radius clip.
        if let clip = layer.clipShape {
            b.line(".clipShape(\(shapeExpr(clip, layer)))")
        } else if s.cornerRadius > 0 && !selfPaints {
            b.line(".clipShape(RoundedRectangle(cornerRadius: \(tokenExpr(s.tokens.cornerRadius, document: document) ?? fmt(s.cornerRadius))))")
        }
        if let mask = layer.mask, layer.kind != .mask {
            b.line(".mask(\(shapeExpr(mask.shape, layer)))")
        }
        if let transform = layer.assetTransform {
            if let crop = transform.crop, !crop.isIdentity {
                b.line("// Crop metadata: x \(fmt(crop.x)), y \(fmt(crop.y)), width \(fmt(crop.width)), height \(fmt(crop.height))")
                b.line(".clipped()")
            }
            if transform.scaleX != 1 || transform.scaleY != 1 || transform.flipHorizontal || transform.flipVertical {
                b.line(".scaleEffect(x: \(fmt(transform.effectiveScaleX)), y: \(fmt(transform.effectiveScaleY)))")
            }
            if transform.blendMode != .normal {
                b.line(".blendMode(.\(transform.blendMode.swiftUIName))")
            }
            if let texture = transform.textureOverlayID, !texture.isEmpty {
                b.line("// Texture overlay hook: \(texture)")
            }
        }
        if let border = s.borderColor, s.borderWidth > 0, !selfPaints {
            b.line(".overlay(RoundedRectangle(cornerRadius: \(fmt(s.cornerRadius)))")
            b.indented { $0.line(".stroke(\(colorExpr(border)), lineWidth: \(fmt(s.borderWidth))))") }
        }
        if let shadow = s.shadow {
            if let name = tokenName(s.tokens.shadow, document: document) {
                b.line(".shadow(color: DesignTokens.\(name).color, radius: DesignTokens.\(name).radius, x: DesignTokens.\(name).x, y: DesignTokens.\(name).y)")
            } else {
                b.line(".shadow(color: \(colorExpr(shadow.color)), radius: \(fmt(shadow.radius)), x: \(fmt(shadow.x)), y: \(fmt(shadow.y)))")
            }
        }
        if s.blurRadius > 0 {
            b.line(".blur(radius: \(fmt(s.blurRadius)))")
        }
        if s.rotationDegrees != 0 {
            b.line(".rotationEffect(.degrees(\(fmt(s.rotationDegrees))))")
        }
        if s.opacity < 1 {
            b.line(".opacity(\(fmt(s.opacity)))")
        }
        b.line(".position(x: \(fmt(layer.frame.midX)), y: \(fmt(layer.frame.midY)))")
        if layer.isAccessibilityHidden {
            b.line(".accessibilityHidden(true)")
        }
        let anchor = layer.binding?.anchorID ?? layer.id.uuidString
        b.line(".accessibilityIdentifier(\(quoted(anchor)))")
    }

    // MARK: - Vector shape / line / polygon / gradient emission

    private func isVectorKind(_ kind: LayerKind) -> Bool {
        switch kind {
        case .shape, .line, .vectorPath, .polygon, .gradient, .mask: return true
        default: return false
        }
    }

    /// A SwiftUI shape initializer expression for a `ShapeKind`.
    private func shapeExpr(_ kind: ShapeKind, _ layer: Layer) -> String {
        let radius = layer.style.cornerRadius > 0 ? layer.style.cornerRadius : 10
        switch kind {
        case .rectangle, .divider: return "Rectangle()"
        case .roundedRectangle, .card, .glassPanel, .callout:
            return "RoundedRectangle(cornerRadius: \(fmt(radius)))"
        case .ellipse: return "Ellipse()"
        case .capsule: return "Capsule()"
        case .star: return "RoundedRectangle(cornerRadius: \(fmt(radius)))" // stars render via Path in content
        }
    }

    private func emitShape(_ kind: ShapeKind, _ layer: Layer, into b: inout SourceBuilder) {
        if kind == .star {
            emitStarPath(layer, into: &b)
            return
        }
        b.line(shapeExpr(kind, layer))
        b.indented { b in
            if kind == .glassPanel {
                b.line(".fill(.ultraThinMaterial)")
            } else {
                b.line(".fill(\(fillExpr(layer)))")
            }
            if let border = layer.style.borderColor, layer.style.borderWidth > 0 {
                b.line(".overlay(\(shapeExpr(kind, layer)).stroke(\(colorExpr(border)), lineWidth: \(fmt(layer.style.borderWidth))))")
            }
        }
    }

    private func emitLine(_ layer: Layer, into b: inout SourceBuilder) {
        let line = layer.line ?? LineSpec(start: VPoint(x: 0, y: layer.frame.height / 2),
                                          end: VPoint(x: layer.frame.width, y: layer.frame.height / 2))
        b.block("Path { path in") { b in
            b.line("path.move(to: CGPoint(x: \(fmt(line.start.x)), y: \(fmt(line.start.y))))")
            switch line.effectiveConnector {
            case .straight:
                b.line("path.addLine(to: CGPoint(x: \(fmt(line.end.x)), y: \(fmt(line.end.y))))")
            case .curved:
                let c1 = line.controlPoint1 ?? VPoint(x: layer.frame.width * 0.33, y: line.start.y)
                let c2 = line.controlPoint2 ?? VPoint(x: layer.frame.width * 0.66, y: line.end.y)
                b.line("path.addCurve(to: CGPoint(x: \(fmt(line.end.x)), y: \(fmt(line.end.y))), control1: CGPoint(x: \(fmt(c1.x)), y: \(fmt(c1.y))), control2: CGPoint(x: \(fmt(c2.x)), y: \(fmt(c2.y))))")
            case .elbow:
                let elbow = VPoint(x: line.end.x, y: line.start.y)
                b.line("path.addLine(to: CGPoint(x: \(fmt(elbow.x)), y: \(fmt(elbow.y))))")
                b.line("path.addLine(to: CGPoint(x: \(fmt(line.end.x)), y: \(fmt(line.end.y))))")
            }
            if line.arrowStart {
                emitArrowhead(into: &b, tip: line.start, from: line.end)
            }
            if line.arrowEnd {
                emitArrowhead(into: &b, tip: line.end, from: line.start)
            }
        }
        b.line("}")
        let width = layer.style.borderWidth > 0 ? layer.style.borderWidth : 2
        let dash = line.isDotted ? ", dash: [1, \(fmt(max(2, width * 2)))]"
            : (line.dashed ? ", dash: [6, 4]" : "")
        let stroke = "StrokeStyle(lineWidth: \(fmt(width)), lineCap: .\(line.effectiveCap.rawValue), lineJoin: .\(line.effectiveJoin.rawValue)\(dash))"
        b.indented { $0.line(".stroke(\(strokeColorExpr(layer)), style: \(stroke))") }
    }

    private func emitVectorPath(_ layer: Layer, into b: inout SourceBuilder) {
        let path = layer.vectorPath ?? VectorPathSpec()
        b.block("Path { path in") { b in
            guard let first = path.anchors.first else { return }
            b.line("path.move(to: CGPoint(x: \(fmt(first.point.x)), y: \(fmt(first.point.y))))")
            for pair in zip(path.anchors, path.anchors.dropFirst()) {
                let previous = pair.0
                let current = pair.1
                if let c1 = previous.handleOut, let c2 = current.handleIn {
                    b.line("path.addCurve(to: CGPoint(x: \(fmt(current.point.x)), y: \(fmt(current.point.y))), control1: CGPoint(x: \(fmt(c1.x)), y: \(fmt(c1.y))), control2: CGPoint(x: \(fmt(c2.x)), y: \(fmt(c2.y))))")
                } else {
                    b.line("path.addLine(to: CGPoint(x: \(fmt(current.point.x)), y: \(fmt(current.point.y))))")
                }
            }
            if path.isClosed { b.line("path.closeSubpath()") }
        }
        b.line("}")
        b.indented { b in
            if let fill = path.fillColor {
                b.line(".fill(\(colorExpr(fill)))")
            } else {
                let stroke = path.strokeColor.map(colorExpr) ?? "Color.primary"
                b.line(".stroke(\(stroke), lineWidth: \(fmt(path.strokeWidth)))")
            }
        }
    }

    private func emitArrowhead(into b: inout SourceBuilder, tip: VPoint, from: VPoint) {
        let angle = atan2(tip.y - from.y, tip.x - from.x)
        let length = 10.0
        let spread = Double.pi / 7
        let a = VPoint(x: tip.x - cos(angle - spread) * length,
                       y: tip.y - sin(angle - spread) * length)
        let c = VPoint(x: tip.x - cos(angle + spread) * length,
                       y: tip.y - sin(angle + spread) * length)
        b.line("path.move(to: CGPoint(x: \(fmt(a.x)), y: \(fmt(a.y))))")
        b.line("path.addLine(to: CGPoint(x: \(fmt(tip.x)), y: \(fmt(tip.y))))")
        b.line("path.addLine(to: CGPoint(x: \(fmt(c.x)), y: \(fmt(c.y))))")
    }

    private func emitPolygon(_ layer: Layer, into b: inout SourceBuilder) {
        let spec = layer.polygon ?? PolygonSpec()
        let points = polygonPoints(width: layer.frame.width, height: layer.frame.height, spec: spec)
        b.block("Path { path in") { b in
            for (i, p) in points.enumerated() {
                let op = i == 0 ? "move(to:" : "addLine(to:"
                b.line("path.\(op) CGPoint(x: \(fmt(p.x)), y: \(fmt(p.y))))")
            }
            b.line("path.closeSubpath()")
        }
        b.line("}")
        b.indented { b in
            b.line(".fill(\(fillExpr(layer)))")
            if let border = layer.style.borderColor, layer.style.borderWidth > 0 {
                b.line(".overlay(\(polygonOverlay(points)).stroke(\(colorExpr(border)), lineWidth: \(fmt(layer.style.borderWidth))))")
            }
        }
    }

    private func emitStarPath(_ layer: Layer, into b: inout SourceBuilder) {
        let spec = PolygonSpec(sides: 5, rotationDegrees: layer.style.rotationDegrees, starInnerRatio: 0.4)
        let points = polygonPoints(width: layer.frame.width, height: layer.frame.height, spec: spec)
        b.block("Path { path in") { b in
            for (i, p) in points.enumerated() {
                let op = i == 0 ? "move(to:" : "addLine(to:"
                b.line("path.\(op) CGPoint(x: \(fmt(p.x)), y: \(fmt(p.y))))")
            }
            b.line("path.closeSubpath()")
        }
        b.line("}")
        b.indented { $0.line(".fill(\(fillExpr(layer)))") }
    }

    private func polygonOverlay(_ points: [VPoint]) -> String {
        // Inline a Path expression for the stroke overlay.
        var s = "Path { path in "
        for (i, p) in points.enumerated() {
            s += i == 0 ? "path.move(to: CGPoint(x: \(fmt(p.x)), y: \(fmt(p.y)))); "
                        : "path.addLine(to: CGPoint(x: \(fmt(p.x)), y: \(fmt(p.y)))); "
        }
        s += "path.closeSubpath() }"
        return s
    }

    /// Computes polygon/star vertices in the layer's local frame.
    private func polygonPoints(width: Double, height: Double, spec: PolygonSpec) -> [VPoint] {
        let cx = width / 2, cy = height / 2
        let rx = width / 2, ry = height / 2
        let n = Swift.max(3, spec.sides)
        let rot = spec.rotationDegrees * .pi / 180
        var pts: [VPoint] = []
        if let inner = spec.starInnerRatio {
            for i in 0..<(n * 2) {
                let angle = -Double.pi / 2 + rot + Double(i) * .pi / Double(n)
                let r = i % 2 == 0 ? 1.0 : inner
                pts.append(VPoint(x: cx + cos(angle) * rx * r, y: cy + sin(angle) * ry * r))
            }
        } else {
            for i in 0..<n {
                let angle = -Double.pi / 2 + rot + Double(i) * 2 * .pi / Double(n)
                pts.append(VPoint(x: cx + cos(angle) * rx, y: cy + sin(angle) * ry))
            }
        }
        return pts
    }

    /// Fill expression: gradient if set, else background colour, else neutral.
    private func fillExpr(_ layer: Layer) -> String {
        if let g = layer.style.gradient { return gradientExpr(g) }
        if let bg = layer.style.backgroundColor { return colorExpr(bg) }
        return "Color.gray.opacity(0.25)"
    }

    private func strokeColorExpr(_ layer: Layer) -> String {
        if let c = layer.style.borderColor { return colorExpr(c) }
        if let c = layer.style.foregroundColor { return colorExpr(c) }
        return "Color.primary"
    }

    /// A SwiftUI gradient expression for a `GradientSpec`.
    private func gradientExpr(_ g: GradientSpec) -> String {
        let stops = g.stops.map {
            "Gradient.Stop(color: \(colorExpr($0.color)), location: \(fmt($0.location)))"
        }.joined(separator: ", ")
        let gradient = "Gradient(stops: [\(stops)])"
        switch g.kind {
        case .linear:
            return "LinearGradient(gradient: \(gradient), startPoint: \(unitPoint(g.startPoint)), endPoint: \(unitPoint(g.endPoint)))"
        case .radial:
            return "RadialGradient(gradient: \(gradient), center: .center, startRadius: 0, endRadius: 200)"
        case .angular:
            return "AngularGradient(gradient: \(gradient), center: .center)"
        }
    }

    private func unitPoint(_ p: VPoint) -> String {
        "UnitPoint(x: \(fmt(p.x)), y: \(fmt(p.y)))"
    }

    // MARK: - Formatting helpers

    private func colorExpr(_ c: VColor) -> String {
        "Color(.sRGB, red: \(fmt(c.red)), green: \(fmt(c.green)), blue: \(fmt(c.blue)), opacity: \(fmt(c.alpha)))"
    }

    private func tokenExpr(_ id: UUID?, document: Document) -> String? {
        guard let id, let token = document.designToken(id: id) else { return nil }
        return "DesignTokens.\(token.swiftName)"
    }

    private func tokenName(_ id: UUID?, document: Document) -> String? {
        guard let id, let token = document.designToken(id: id) else { return nil }
        return token.swiftName
    }

    private func quoted(_ s: String) -> String {
        let escaped = s
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    private func fmt(_ d: Double) -> String {
        if d == d.rounded() { return String(Int(d)) }
        return String(format: "%.2f", d)
    }

    private func sanitizeType(_ name: String) -> String {
        let allowed = name.filter { $0.isLetter || $0.isNumber || $0 == "_" }
        return allowed.isEmpty ? "CustomView" : allowed
    }
}

private extension LayerBlendMode {
    var swiftUIName: String {
        switch self {
        case .normal: return "normal"
        case .multiply: return "multiply"
        case .screen: return "screen"
        case .overlay: return "overlay"
        case .darken: return "darken"
        case .lighten: return "lighten"
        }
    }
}
